### ISSUE TITLE
As a developer, I want to enhance my working experience on Windows after Mac OS, in order to be more productive

### ISSUE THREAD

**Issue by aruppert** [aruppert/recreatio#2]
### Criteria
- [ ] thinking about solutions like eg changing key shortcuts
- [ ] installing the exact same keylayout on windows
- [ ] finding an easier solution to the german vowel mutation like on Mac (option + u + LETTER) 

### To-Do
- [ ] research
